# Generated by Django 6.0.8 on 2026-08-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID del calendario de Google compartido con la cuenta de servicio', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('8_dias', '8 días antes'), ('1_dia', '1 día antes')], max_length=10)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='calendario.cita')),
            ],
            options={
                'ordering': ['-generado_en'],
                'unique_together': {('cita', 'tipo')},
            },
        ),
    ]
