# Generated by Django 6.0.8 on 2026-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_cita_google_event_id_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitente',
            name='calendario_compartido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remitente',
            name='calendario_compartido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
