# Generated by Django 6.0.8 on 2026-08-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_remitente_calendario_compartido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
