# Generated by Django 6.0.8 on 2026-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_financiera_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, help_text='JID del grupo de WhatsApp de esta sede (ej: 12036xxxxxx-xxxx@g.us)', max_length=255, null=True),
        ),
    ]
