# Generated by Django 6.0.8 on 2026-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_sede_whatsapp_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='confirmado_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmado_whatsapp_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='whatsapp_mensaje_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
