# Generated by Django 6.0.8 on 2026-08-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0008_cita_confirmado_whatsapp_cita_confirmado_whatsapp_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='whatsapp_group_id',
        ),
    ]
