# Generated by Django 6.0.8 on 2026-08-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0009_remove_sede_whatsapp_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, help_text='ID del grupo de WhatsApp, formato: 1234567890-1234567890@g.us', max_length=100, null=True),
        ),
    ]
